# fly.toml app configuration file generated for socialapp-zb on 2023-10-22T01:22:24+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "socialapp-zb"
primary_region = "sin"

[build]
  image = "zakariabijoy/socialapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="zakariabijoy"
  CloudinarySettings__ApiKey="372896596436432"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
